//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcraft.Ace.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tcraft.Ace.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided number is not in the acceptable range. Please provide a number between 0 and 50..
        /// </summary>
        public static string FibonacciNumberNotInRange {
            get {
                return ResourceManager.GetString("FibonacciNumberNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request. Please specify a limit for prime numbers. 0 is not a valid limit. Use &apos;limit&apos; query string parameter to specify the limit. For example: &apos;{0}?limit=100&apos;..
        /// </summary>
        public static string InvalidPrimeNumberLimitRequest {
            get {
                return ResourceManager.GetString("InvalidPrimeNumberLimitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request. Please specify a temperature to convert. Use &apos;celsius&apos; query string parameter to convert from Celsius to Kelvin or &apos;kelvin&apos; query string parameter to convert from Kelvin to Celsius. For example: &apos;{0}?celsius=25&apos; or &apos;{0}?kelvin=298.15&apos;..
        /// </summary>
        public static string InvalidTemperatureConversionRequest {
            get {
                return ResourceManager.GetString("InvalidTemperatureConversionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided limit is not in the acceptable range. Please provide a limit between 1 and 10000..
        /// </summary>
        public static string PrimeNumberLimitNotInRange {
            get {
                return ResourceManager.GetString("PrimeNumberLimitNotInRange", resourceCulture);
            }
        }
    }
}
